### ISSUE TITLE
Load blank images when <7 contributors

### ISSUE THREAD

**Issue by bobheadxi** [sourcerer-io/hall-of-fame#12]
Just an idea, but looks like when you have <7 contributors, on some systems a not-very-nice placeholder is shown:

![blank](https://user-images.githubusercontent.com/23356519/43984962-bcea1888-9cb8-11e8-87cf-ebb9ffd17d2d.PNG)

Example is from this repo. https://github.com/sourcerer-io/hall-of-fame#contributing

Potential solution could be to serve up a blank image

**Comment by sergey48k** [comment]
Just to clarify: GitHub seems to be using some sort of a cache for images linked from READMEs. Occasionally, it does not load those images properly. So they show as they didn't load by the browser. This behavior happens for shields/badges, pictures in repo, etc. We are no different.
