### ISSUE TITLE
usernames in title tags? also in links?

### ISSUE THREAD

**Issue by benatkin** [sourcerer-io/hall-of-fame#17]
If the anchor tags or images had usernames on them, using a [title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title), I could hover over them and see the usernames of the users, without clicking on them. This especially helps with users that don't have avatars.

It would also be nice for them to be in the links. If numbers are better for implementing them, they could just be added to the end of the URLs in addition to the numbers but not used by the web server.

**Comment by sergey48k** [comment]
Hi @benatkin ,

Thank you for the suggestions.

Unfortunately, we are limited what Markdown or RST can do. While I definitely want those titles, Markdown does not let me fetch them dynamically.

I will close this now as there is nothing we can do.
