### ISSUE TITLE
Badge is not available

### ISSUE THREAD

**Issue by zonuexe** [sourcerer-io/hall-of-fame#19]
I got follows code from https://sourcerer.io/settings#hof , but it does not seem to be working.

> [![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/0)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/0)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/1)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/1)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/2)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/2)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/3)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/3)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/4)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/4)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/5)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/5)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/6)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/6)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/7)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/7)

```
[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/0)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/0)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/1)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/1)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/2)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/2)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/3)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/3)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/4)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/4)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/5)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/5)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/6)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/6)[![](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/7)](https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/links/7)
```

```
% curl -I https://sourcerer.io/fame/zonuexe/emacs-php/php-mode/images/0
HTTP/2 404
server: nginx/1.13.12
date: Fri, 24 Aug 2018 03:45:16 GMT
x-powered-by: Express
vary: Origin
access-control-allow-credentials: true
cache-control: no-cache
cache-control: no-store
cache-control: must-revalidate
via: 1.1 google
alt-svc: clear
```

refs https://github.com/emacs-php/php-mode/pull/481

**Comment by sergey48k** [comment]
hi @zonuexe 

thank you for the report. looking into it now. will keep you posted.

**Comment by sergey48k** [comment]
the culprit is an error in sourcerer avatar API. it fails to return avatars for new users. investigating. @yandzee

**Comment by sergey48k** [comment]
@zonuexe It's back up, as you can see in your original description of the issue.

**Comment by zonuexe** [comment]
@sergey48k Thank you for the correction, and your great work!
