### ISSUE TITLE
hall of fame should filter bot/app accounts

### ISSUE THREAD

**Issue by chris48s** [sourcerer-io/hall-of-fame#22]
If I generate a hall of fame for this repo https://github.com/badges/shields

[dependabot](https://github.com/apps/dependabot) is included as a contributor:

![hof2](https://user-images.githubusercontent.com/6025893/44864974-f322d780-ac78-11e8-88f2-ad21ec54dc8e.png)

(additionally, the link it generates for the bot's "profile" is https://github.com/dependabot[bot] which is a 404. If anything it should be https://github.com/apps/dependabot )

However, I think if it is possible to identify activity from github app/bot accounts these should ideally be excluded in favour of human contributors.

**Comment by sergey48k** [comment]
Added a fix and released to production: https://github.com/sourcerer-io/hall-of-fame/commit/4ef1aa9fd271b9cde787fc1ab4b5d8b915fc9ba3

[![0](https://sourcerer.io/fame/chris48s/badges/shields/images/0)](https://sourcerer.io/fame/chris48s/badges/shields/links/0)
[![1](https://sourcerer.io/fame/chris48s/badges/shields/images/1)](https://sourcerer.io/fame/chris48s/badges/shields/links/1)
[![2](https://sourcerer.io/fame/chris48s/badges/shields/images/2)](https://sourcerer.io/fame/chris48s/badges/shields/links/2)
[![3](https://sourcerer.io/fame/chris48s/badges/shields/images/3)](https://sourcerer.io/fame/chris48s/badges/shields/links/3)
[![4](https://sourcerer.io/fame/chris48s/badges/shields/images/4)](https://sourcerer.io/fame/chris48s/badges/shields/links/4)
[![5](https://sourcerer.io/fame/chris48s/badges/shields/images/5)](https://sourcerer.io/fame/chris48s/badges/shields/links/5)
[![6](https://sourcerer.io/fame/chris48s/badges/shields/images/6)](https://sourcerer.io/fame/chris48s/badges/shields/links/6)
[![7](https://sourcerer.io/fame/chris48s/badges/shields/images/7)](https://sourcerer.io/fame/chris48s/badges/shields/links/7)
