### ISSUE TITLE
Hall of fame doesn't seems to be working

### ISSUE THREAD

**Issue by thetutlage** [sourcerer-io/hall-of-fame#31]
Hello! First of all, Sourcerer and Hall of fame both are great services :)

I am trying to add HOF to [adonis-framework](https://github.com/adonisjs/adonis-framework/tree/v5) and for some reasons, it's not working. I did wait for more than an hour and still the images returns `404`.

<img width="1177" alt="screenshot 2019-01-22 at 5 06 19 pm" src="https://user-images.githubusercontent.com/1706381/51533160-0f155880-1e68-11e9-826b-7417d1af1146.png">

**Comment by sergey48k** [comment]
Hi @thetutlage 

thank you! we will look into this today.

= Sergey

**Comment by sergey48k** [comment]
hi @thetutlage ,

Could you try again? I just pushed a bug fix.

**Comment by thetutlage** [comment]
Works like a charm. Thanks 😄
