### ISSUE TITLE
Couldn't use hall of fame for an organization repo

### ISSUE THREAD

**Issue by humb1t** [sourcerer-io/hall-of-fame#36]
`Add Hall of Fame to your repo:` in settings lists only personal repositories without repositories from organizations.

**Comment by sergey48k** [comment]
Hi @humb1t 

It should list all repos that you authorized Sourcerer to see. When you sign up for Sourcerer, it asks for permissions to see public repos of the orgs you are associated with. You can check if Sourcerer has access in GitHub settings. It's possible that someone else from your org clicked 'no', and GitHub made this setting applied to everyone. It's pretty annoying but it's how GitHub works.

If you think that Sourcerer has access to your org public repos, please let me know and I'll debug.

**Comment by humb1t** [comment]
Hi @sergey48k - 
![image](https://user-images.githubusercontent.com/5635032/54416736-ab960180-4719-11e9-95b1-08170520f01e.png) it seems like everything is okay, but https://sourcerer.io/settings#processing showed no repositories from the organization.

**Comment by humb1t** [comment]
Hi, @sergey48k can you check our case? https://github.com/SamaraITCommunity - organization.

**Comment by sergey48k** [comment]
Looking. Will keep you posted.

**Comment by sergey48k** [comment]
@humb1t if you have a specific repository in mind, I can add it on our end using our admin interface.

**Comment by humb1t** [comment]
@sergey48k thank you, it's https://github.com/SamaraITCommunity/site

**Comment by humb1t** [comment]
@sergey48k thank you, it's https://github.com/SamaraITCommunity/site

**Comment by sergey48k** [comment]
@humb1t interesting. I also get unauthorized from github when adding your repo manually. any chance that you disabled github access to sourcerer? any chance you run a batch job under your github identity that uses up the github rate limit?

**Comment by humb1t** [comment]
@sergey48k - no, access still here: 
![image](https://user-images.githubusercontent.com/5635032/54590972-a9e27b80-4a42-11e9-8b73-c73853cade49.png)

The only job is our Travis CI and GitHub pages deployment, but it's a rare case. 

Thank you for help, maybe it would be fixed in future releases.

**Comment by sergey48k** [comment]
Hi @humb1t ,

I tried my own user, and it works just fine. Feel free to use the code below with my identity. Or if you have someone else in your group whose identity you want to use, just let me know. I suspect there is something strange with your account but I don't know what.

[![0](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/0)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/0)
[![1](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/1)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/1)
[![2](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/2)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/2)
[![3](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/3)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/3)
[![4](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/4)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/4)
[![5](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/5)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/5)
[![6](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/6)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/6)
[![7](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/images/7)](https://sourcerer.io/fame/sergey48k/SamaraITCommunity/site/links/7)

**Comment by humb1t** [comment]
@sergey48k thank you!
