### ISSUE TITLE
My repo is being skipped due to "No contributions"

### ISSUE THREAD

**Issue by nuttyartist** [sourcerer-io/hall-of-fame#43]
Hello, I really like the idea and would like to use it in my repo https://github.com/nuttyartist/notes, but it seems like sourcerer is skipping my notes repo due to wrongly identifying "No contributions". Can you help solve that?

Thanks!

**Comment by sergey48k** [comment]
hi @nuttyartist 

This usually happens when sourcerer does not know about all email addresses you used for commits. Try the following:

Locally, in your repo:
```
git log | grep Author | sort | uniq
```
This should give you a list of emails. Then go to https://sourcerer.io/settings#emails and make sure all those emails are listed.

**Comment by nuttyartist** [comment]
There many emails, can't they be listed automatically?

**Comment by nuttyartist** [comment]
Also, will each of the user's email I put (contributors') will need to confirm their email?

**Comment by redbitshift** [comment]
The idea is you add your emails because it's your profile. Please don't add your coworker emails.

**Comment by nuttyartist** [comment]
Gotcha! Now it's working, thanks! :)
